### ISSUE TITLE
[Study] CI/CD 실습 공부

### ISSUE THREAD

**Issue by InSeong23** [nhnacademy-aiot2-javame/study#4]
# 📚 공부 기록 - {{CI/CD 실습 공부}}

- 📅 날짜: {{2025-04-09}}
- ✍️ 작성자: {{임성인}}

---

## ✨ 오늘의 내용 요약
{{CI/CD 실습한 내용입니다}}

---

## 📖 상세 내용
{{

개인 로컬 환경에서 키를 생성하기 위해 터미널에서 작업합니다

{
자동화 배포를 위한 ssh key 등록 및 생성

로컬 환경에서 키를 만들 폴더를 생성.
mkdir keygen

keygen폴더에서 
ssh-keygen -t rsa -f ./github_rsa 후 모두 enter

사용하여 개인키와 공개키를 생성 합니다. (github_rsa, github_rsa.pub)

원격 서버에서 
nano, vi같은 편집기를 이용하여서 github_rsa.pub 파일에 
공개키 작성. (또는 ~/.ssh/authorized_keys에 직접 작성)

cat ~/github_rsa.pub >> ~/.ssh/authorized_keys
를 사용하여서 서버에 공개키 등록.

서버에 있는 github_rsa.pub 삭제.

로컬에 있는 개인키는 권한을 소유자만 읽고 수정이 안되게
chmod 400 github_rsa 설정

서버 접속은 ssh -i github_rsa -p 8822 [aiot2-team3@s2.java21.net](mailto:aiot2-team3@s2.java21.net)
로 가능.
}

실습을 위한 리포지토리를 생성후 클론하여 연결해줍니다

리포지토리에서 Setting -Secrets and variables-Actions 를 통해 서버 환경에 맞는 SSH_ID, SSH_IP, SSH_KEY, SSH_PORT를 설정해줍니다  여기서 SSH_KEY는 private key입니다

이후 깃의 Actins 창에서  New workflow 버튼을 통해 'Java with Maven'를 Configure 해주고
기존의 maven.yml을 자신의 환경에 맞게 수정을 해줍니다
서버에 jar파일을 올리기 위한 코드와 원격 서버에 쉘 스크립트 실행을 위한 코드를 추가해줍니다

```
      - name: upload file
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "target/*.jar"
          target: "~/test/"
          rm: false

      - name: execute shell script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: "test/startup.sh"
```
프로젝트에서 application.properties 에서 서버 포트를 설정해주고 commit 해보면 
깃에서 Action에서 CI/CD로 workflow가 잘 작동하면 성공

}}

```예시 코드가 있다면 이렇게 넣어주세요.```

---

## 🖼️ 참고 이미지  
> 이미지 첨부는 `![이미지 설명](이미지 경로)`  
예시:
![예시 이미지](./images/example.png)

---

## 📎 참고 파일  
> 파일은 프로젝트 내 폴더에 저장한 뒤 링크로 연결  
예시:
[예시 파일 다운로드](./files/example.pdf)

---

## 💡 느낀 점 / 다음 목표
- {{오늘 공부하면서 느낀 점이나 배운 점을 간단히 작성}}
- {{다음 공부 계획 또는 궁금한 점 정리}}

---
